// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lefhzuwhoybxgrefcxba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxlZmh6dXdob3lieGdyZWZjeGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMzU4NzYsImV4cCI6MjA3MTgxMTg3Nn0.5jspVk4iEQJl5dVEGhtrV1wNZQlpselFqBMTJCnndCQ";


// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});