import { Route } from "lucide-react";
import { RouteAwareCrudTable } from "@/components/crud/RouteAwareCrudTable";
import { CrudTableConfig } from "@/components/crud/CrudTable";

const routesConfig: CrudTableConfig = {
  table: "routes",
  title: "Routes",
  description:
    "Manage shipping routes between facilities (warehouse to distribution center) and regions (region to region)",
  primaryKey: "route_id",
  displayColumns: [
    "route_code",
    "route_type",
    "warehouse_name",
    "distribution_center_name",
    "route_region_value",
    "distance_km",
    "estimated_time_hrs",
  ],
  searchableColumns: [
    "route_code",
    "route_type",
    "warehouse_name",
    "distribution_center_name",
    "distance_km",
    "estimated_time_hrs",
  ],
  icon: Route,
  fields: [
    { name: "route_code", label: "Route Code", type: "text", readonly: true },
    {
      name: "route_type",
      label: "Route Type",
      type: "select",
      required: true,
      options: [
        { value: "warehouse_to_dc", label: "Warehouse → Distribution Center" },
        { value: "warehouse_to_self", label: "Warehouse → Self Warehouse" },
        { value: "self_to_dc", label: "Self Warehouse → Distribution Center" },
        { value: "region_to_region", label: "Region → Region" },
      ],
      placeholder: "Choose route type...",
    },
    {
      name: "warehouse_id",
      label: "Warehouse",
      type: "foreign_key",
      required: true,
      foreignTable: "supplier_warehouses",
      foreignKeyField: "warehouse_id",
      foreignDisplayField: "warehouse_name",
      conditionalDisplay: { dependsOn: "route_type", showWhen: ["warehouse_to_dc", "warehouse_to_self"] },
    },
    {
      name: "distribution_center_id",
      label: "Distribution Center",
      type: "foreign_key",
      required: true,
      foreignTable: "customer_distribution_centers",
      foreignKeyField: "distribution_center_id",
      foreignDisplayField: "distribution_center_name",
      conditionalDisplay: { dependsOn: "route_type", showWhen: ["warehouse_to_dc", "self_to_dc"] },
    },
    {
      name: "self_warehouse_id",
      label: "Self Warehouse",
      type: "foreign_key",
      required: true,
      foreignTable: "self_warehouses",
      foreignKeyField: "warehouse_id",
      foreignDisplayField: "warehouse_name",
      conditionalDisplay: { dependsOn: "route_type", showWhen: ["warehouse_to_self", "self_to_dc"] },
    },
    {
      name: "origin_route_id",
      label: "Origin Region",
      type: "foreign_key",
      required: true,
      foreignTable: "routes_by_regions",
      foreignKeyField: "id",
      foreignDisplayField: "value",
      conditionalDisplay: { dependsOn: "route_type", showWhen: "region_to_region" },
    },
    {
      name: "destination_route_id",
      label: "Destination Region",
      type: "foreign_key",
      required: true,
      foreignTable: "routes_by_regions",
      foreignKeyField: "id",
      foreignDisplayField: "value",
      conditionalDisplay: { dependsOn: "route_type", showWhen: "region_to_region" },
    },
    // Auto-filled read-only fields (only for warehouse routes)
    {
      name: "origin",
      label: "Origin",
      type: "text",
      readonly: true,
      placeholder: "Auto-filled from warehouse",
      conditionalDisplay: { dependsOn: "route_type", showWhen: ["warehouse_to_dc", "warehouse_to_self", "self_to_dc"] },
    },
    {
      name: "origin_supplier",
      label: "Origin Details",
      type: "text",
      readonly: true,
      placeholder: "Auto-filled from warehouse",
      conditionalDisplay: { dependsOn: "route_type", showWhen: ["warehouse_to_dc", "warehouse_to_self", "self_to_dc"] },
    },
    {
      name: "destination",
      label: "Destination",
      type: "text",
      readonly: true,
      placeholder: "Auto-filled from destination",
      conditionalDisplay: { dependsOn: "route_type", showWhen: ["warehouse_to_dc", "warehouse_to_self", "self_to_dc"] },
    },
    {
      name: "destination_customer",
      label: "Destination Details",
      type: "text",
      readonly: true,
      placeholder: "Auto-filled from destination",
      conditionalDisplay: { dependsOn: "route_type", showWhen: ["warehouse_to_dc", "warehouse_to_self", "self_to_dc"] },
    },
    {
      name: "distance_km",
      label: "Distance (km)",
      type: "number",
      min: 0,
      step: 0.01,
      placeholder: "Enter distance in kilometers",
    },
    {
      name: "estimated_time_hrs",
      label: "Estimated Time (hrs)",
      type: "number",
      min: 0,
      step: 0.01,
      placeholder: "Enter estimated time in hours",
    },
    {
      name: "route_by_region_id",
      label: "Region",
      type: "foreign_key",
      required: false,
      foreignTable: "routes_by_regions",
      foreignKeyField: "id",
      foreignDisplayField: "value",
    },
  ],
};

export default function RoutesPage() {
  return <RouteAwareCrudTable config={routesConfig} />;
}
